name: Automated Python Test

on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Test with Multiple Numbers
        run: |
          python find_lowest_number.py ../test_data/test1_input.txt ../output1.txt
          diff ../output1.txt ../test_data/test1_expected.txt

      - name: Test with Single Number
        run: |
          python find_lowest_number.py ../test_data/test2_input.txt ../output2.txt
          diff ../output2.txt ../test_data/test2_expected.txt

      - name: Test with Blank File
        run: |
          python find_lowest_number.py ../test_data/test3_input.txt ../output3.txt
          diff ../output3.txt ../test_data/test3_expected.txt
